### ISSUE TITLE
DB importation notice

### ISSUE THREAD

**Issue by Mknan-fms** [osman-moh/water#3]
When importing the DB tables, the following changes are required for the process to work perfectly:

- Rename table users_type ==> user_type

- Rename column "type" in users table into "user_type_id"

- In reports table rename column "location -> location_id", "report_type -> report_type_id", "report_sub_type -> report_sub_type_id" , "report_detail -> report_sub_detail_id", "report_status -> report_status_id"

 @osman-moh

**Comment by osman-moh** [comment]
Ok ! done  . Mknan Big bos for github management.
